site_name: OEPS Data Ecosystem
nav:
  - Background:
    - legacy-migration.md
  - Guides:
    - guides/install-explorer.md
    - guides/install-backend.md
    - guides/getting-started-with-cli.md
    - guides/provisioning-oeps-explorer.md
    - guides/adding-data-to-oeps.md
    - guides/creating-data-packages.md
    - guides/interacting-with-bigquery.md
    - guides/generating-derived-documentation.md
    - guides/writing-documentation.md
  - Registry:
    - registry/index.md
    - registry/metadata.md
    - registry/variables.md
    - registry/table-sources.md
    - registry/geodata-sources.md
  - CLI:
    - reference/cli/command-line-reference.md
plugins:
  - search
  - glightbox
markdown_extensions:
  - markdown.extensions.admonition
  - toc
theme:
  name: readthedocs
docs_dir: ./src
site_dir: ./output