site_name: OEPS Data Ecosystem
nav:
  - Background:
    - index.md
    - legacy-migration.md
  - Data Contributors:
    - guides/adding-data-overview.md
    - guides/preparing-csv-data.md
    - guides/creating-metadata-and-variables.md
  - OEPS Explorer:
    - guides/install-explorer.md
    - guides/provisioning-oeps-explorer.md
  - OEPS Backend:
    - guides/install-backend.md
    - guides/getting-started-with-cli.md
    - guides/merging-data-into-oeps.md
    - guides/creating-data-packages.md
    - guides/interacting-with-bigquery.md
    - reference/cli/command-line-reference.md
  - Registry:
    - registry/index.md
    - registry/data-model.md
    - registry/current-content.md
  - Documentation:
    - guides/writing-documentation.md
    - guides/generating-derived-documentation.md
plugins:
  - search
  - glightbox
markdown_extensions:
  - markdown.extensions.admonition
  - toc
theme:
  name: readthedocs
docs_dir: ./src
site_dir: ./output